[package]
name = "spotify_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
gtk = "0.17.1"
rspotify = "0.11.7"
